# ctrl_calibration_generate_job.sub
# This job will be submitted in each iterative, using ctrl_calibration_generate.sh to invoke
#   ctrl_calibration_generate.py to generate individuals (i.e., multiple calibration.cal files)
#   and worker_jobs.dag (which will submit multiple single model jobs).

universe   = vanilla
executable = ctrl_calibration_generate.sh
# Do not test the "executable" in the login point
transfer_executable = false

# Use Apptainer to run our program
# container_image command will automatically transfer .sif file from /staging to execution point,
# and run '<executable> <arguments>' within the container
container_image = osdf:///chtc/staging/lzhu267/swatplus_utility-0.2.1.sif

preserve_relative_paths = true
transfer_input_files = multi_runs/gen_$(iter_index),iteration.state,ctrl_calibration_generate.sh,param_defs.txt,aqu_combinations.json,hru_combinations.json,channel_combinations.json,observed.tar.gz,TxtInOut.tar.gz,__init__.py,calibration,utils

# Transfer multi_runs folder, workers' dag, and the critical state for indicating the next DAG step
transfer_output_files = worker_jobs_current.dag, multi_runs/gen_$(iter_index), iteration.state

# Use this to ensure the updated iteration.state is also transferred back
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

request_cpus   = 1
request_memory = 256 MB
request_disk   = 2 GB

# Log using the DAG Node name (PREPARE_NEXT_GEN)
log    = dag_logs/ctrl_calibration_generate_job_$(iter_index).log
output = dag_logs/ctrl_calibration_generate_job_$(iter_index).out
error  = dag_logs/ctrl_calibration_generate_job_$(iter_index).err

queue 1
